[build]
NODE_VERSION = 14


[build.production]
YARN_VERSION = "1.12.1"
NPM_VERSION = "6.4.1" 
command = "yarn build"
publish = "dist"

[deploy-preview]
command = "yarn build:preview"

# Hugo Netlify configuration
[production.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[split1]
command = "hugo --gc --minify --enableGitInfo"

[split1.production]
HUGO_VERSION = "0.87.0"
HUGO_ENV = "production"


[branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[branch-deploy.production]
HUGO_VERSION = "0.87.0"

[next.environment]
HUGO_ENABLEGITINFO = "true"