[build.production]
NODE_VERSION = 14
YARN_VERSION = "1.12.1"
NPM_VERSION = "6.4.1" 

[build.production]
command = "yarn build"
publish = "dist"

[context.deploy-preview]
command = "yarn build:preview"

# Hugo Netlify configuration
[context.production.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.production]
HUGO_VERSION = "0.87.0"
HUGO_ENV = "production"


[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.production]
HUGO_VERSION = "0.87.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"